version: '3.8'

services:
  server:
    build:
      context: .
      target: development
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file: "DockerEnv/Api.env"
  idp:
    image: quay.io/keycloak/keycloak:26.0.6
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
  database:
    image: mysql:latest
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=Alexandria
      - MYSQL_USER=standard_user
    env_file: "DockerEnv/MySql.env"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data:
  keycloak-data:
